### PR TITLE
Feature/refactor inputs to have unique date

### PR DESCRIPTION
**Pull request by mischa-s**

### CODE REVIEW

**Comment by mischa-s** [comment]
I still have more work to do on this but wanted to push up what I've been doing

**Comment by dlouise64** [comment]
@mischa-s awesome :). Theres some issues with using ETERNITY though which is why I used months.

**Comment by mischa-s** [comment]
@dlouise64 I've now got enough of this done that I'd like to merge it into your branch/master, can you review please. What are the eternity issues? I've tested this code has been tested against openfisca and chatted with Hamish and it seems important for things that we aren't going to use dates for that we are clear about that e.g. Eternity rather than leaving arbitrary dates but I am going pretty fast so am probably missing stuff

**Comment by dlouise64** [comment]
@mischa-s I see. That's fine. I'm not sure if you're getting a different result to me or not but I'm seeing this in network.

Screen Shot 2019-03-26 at 8 19 21 AM

**Comment by mischa-s** [comment]
Oh yeah sorry @dlouise64,  @verbman  and I changed that yesterday because it was wrong in openfisca, will push that change to the openfisca branch now

**Review by dlouise64 — APPROVED** [review]
👍

**Pull request merged**
